# render.yaml
services:
  - type: web
    name: proyecto-hd
    env: docker
    plan: free
    docker:
      dockerfile: Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: JAVA_OPTS
        value: "-Xmx512m -Xms256m"
    healthCheckPath: /actuator/health
    autoDeploy: true
   